"""empty message

Revision ID: 59fa1629f118
Revises:
Create Date: 2016-11-21 09:34:40.274432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59fa1629f118'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.UnicodeText(), nullable=True),
    sa.Column('original_language', sa.String(), nullable=True),
    sa.Column('translated_text', sa.UnicodeText(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('radlex_annotations', sa.ARRAY(sa.UnicodeText()), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    ### end Alembic commands ###
