"""empty message

Revision ID: 6dbc2bf1923f
Revises: 
Create Date: 2016-12-01 19:02:10.573898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dbc2bf1923f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.UnicodeText(), nullable=True),
    sa.Column('original_language', sa.UnicodeText(), nullable=True),
    sa.Column('translated_text', sa.UnicodeText(), nullable=True),
    sa.Column('category', sa.UnicodeText(), nullable=True),
    sa.Column('radlex_annotations', sa.UnicodeText(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    ### end Alembic commands ###
