"""empty message

Revision ID: e96a7bb945b0
Revises: 
Create Date: 2016-12-04 16:07:41.161722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e96a7bb945b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('original_text', mysql.LONGTEXT(), nullable=True),
    sa.Column('original_language', mysql.TEXT(), nullable=True),
    sa.Column('translated_text', mysql.LONGTEXT(), nullable=True),
    sa.Column('category', mysql.TEXT(), nullable=True),
    sa.Column('radlex_annotations', mysql.LONGTEXT(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    ### end Alembic commands ###
